import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import colors from "../styles/colors";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background text-text h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
